services:
  express-api:
    build: .
    entrypoint: "nodemon --watch \"src/**\" --ext \"ts,json\" --exec \"ts-node src/index.ts\""
    container_name: express-api
    depends_on:
      express-api-db:
        condition: service_healthy
    volumes:
      - ./:/app
      - ./.vol/tmp:/tmp
    links:
      - express-api-db
    ports:
      - "8888:80"

  express-api-db:
    image: mysql:oracle
    container_name: express-api-db
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - ./.vol/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
