# Install VS Code extension rest-client 
# URL: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@Host=http://localhost:8888/api/v1
@AccessToken=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM0NjQ0NzMzLWRlZWEtNDdkOC1iMzVhLTg2ZjMwZmY5NjE4ZSIsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsImZpcnN0TmFtZSI6IlVzZXIiLCJsYXN0TmFtZSI6Ik9uZSIsImlhdCI6MTcxNjU4NTYxNn0.RR-3LfX4uxoF-TXiLXB74viJj927y4Pt1Be-wELnLt8mMbdJdwWeUlzIe-kinZP-c_nu4xuH8O226NfuM2O6TwZYeIBqqlSg6PNrJFg7e6UAWQi_vpRqG9pksYigPC537fdxk85iP07ASErhwa0yGDdu-2XV5dpXuvcNsHfFYhbdJ0Vb_lL7Ve_r5imFCIygIahQ527qmpmiGkbBBwbP-nPmUYydk7k0YEjB-l2HaVJu5wvfis8IVXUlvs9XvaWOOdtucPmN1ZQcp14un2x19uzZTmAafPUCVrKslhFm3_lsrbXcw6DuWR2LGbSZFU2B7qQpExNQ7aK_kPBsjJd7Uw

###########################################
# Auth

### /auth/login
POST {{Host}}/auth/login
content-type: application/json

{
    "email": "user@example.com",
    "password": "Password@1234"
}


### /_authcheck
GET {{Host}}/_authcheck
Authorization: Bearer {{AccessToken}}


### /auth/sign-up
POST {{Host}}/auth/sign-up
content-type: application/json

{
    "email": "johnsmith@foobar.net",
    "password": "Password@1234",
    "firstName": "John",
    "lastName": "Smith",
    "groupName": "",
    "tos": "2024-04-16"
}


###########################################
# Auth

### /user
GET {{Host}}/user
Authorization: Bearer {{AccessToken}}