# Install VS Code extension: rest-client 
# URL: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@Host=http://localhost:8888/api/v1
@AccessToken=null
@GroupA=fdab7a99-2c38-444b-bcb3-f7cef61c275b
@GroupB=be1fcb4e-caf9-41c2-ac27-c06fa24da36a
@User1=c4644733-deea-47d8-b35a-86f30ff9618e
@User2=d700932c-4a11-427f-9183-d6c4b69368f9


###########################################
# DevOps

### /_healthcheck
GET {{Host}}/_healthcheck


###########################################
# Auth

### /auth/login
POST {{Host}}/auth/login
content-type: application/json

{
    "email": "user@example.com",
    "password": "Password@1234",
    "mfaCode": "000000"
}


### /auth/sign-up
POST {{Host}}/auth/sign-up
content-type: application/json

{
    "email": "johnsmith@foobar.net",
    "password": "Password@1234",
    "firstName": "John",
    "lastName": "Smith",
    "groupName": "",
    "tos": "2024-04-16"
}


### /_authcheck
GET {{Host}}/auth/verify-email/000000
Authorization: Bearer {{AccessToken}}


### /auth/forgot
POST {{Host}}/auth/forgot
content-type: application/json

{
    "email": "johnsmith@foobar.net"
}


### /auth/get-user-by-reset-key/:passwordResetKey
GET {{Host}}/auth/get-user-by-reset-key/000000
Authorization: Bearer {{AccessToken}}


### /auth/reset
POST {{Host}}/auth/reset
content-type: application/json

{
    "email": "johnsmith@foobar.net",
    "password": "new-password-4321",
    "passwordResetKey": "000000"
}


### /auth/get-user-by-invite-key/:inviteKey
GET {{Host}}/auth/get-user-by-invite-key/000000
Authorization: Bearer {{AccessToken}}


### /auth/invite
POST {{Host}}/auth/invite
content-type: application/json

{
    "inviteKey": "000000",
    "email": "johnsmith@foobar.net",
    "password": "password@1234",
    "firstName": "John",
    "lastName": "Smith",
    "tos": "2024-04-16"
}


###########################################
# User

### /user
GET {{Host}}/user
Authorization: Bearer {{AccessToken}}


### /user
POST {{Host}}/user
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "firstName": "Alex",
    "lastName": "Jones"
}


### /user/update-password
POST {{Host}}/user/update-password
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "password": "Password@1234",
    "newPassword": "NewPassword!4321"
}


### /user/enable-mfa
POST {{Host}}/user/enable-mfa
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "password": "Password@1234"
}


### /user/confirm-mfa
POST {{Host}}/user/confirm-mfa
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "mfaCode": "917366"
}


### /user/disable-mfa
POST {{Host}}/user/disable-mfa
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "password": "Password@1234"
}

###########################################
# Group

### /groups/:groupID
GET {{Host}}/groups/{{GroupA}}?with=users
Authorization: Bearer {{AccessToken}}


### /groups/:groupID
POST {{Host}}/groups/{{GroupA}}
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "name": "New Group Name"
}


### /groups/:groupID/users/invite
POST {{Host}}/groups/{{GroupA}}/users/invite
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "email": "foobar@gamil.com"
}   


### /groups/:groupID/users/:userID/set-role
POST {{Host}}/groups/{{GroupA}}/users/{{User2}}/set-role
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "role": "Admin"
}   


### /groups/:groupID/users/:userID  
DELETE {{Host}}/groups/{{GroupA}}/users/{{User2}}
Authorization: Bearer {{AccessToken}}
