# Install VS Code extension rest-client 
# URL: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@Host=http://localhost:8888/api/v1
@AccessToken=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM0NjQ0NzMzLWRlZWEtNDdkOC1iMzVhLTg2ZjMwZmY5NjE4ZSIsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsImZpcnN0TmFtZSI6IlVzZXIiLCJsYXN0TmFtZSI6Ik9uZSIsImlhdCI6MTcxODY0Mzk4OH0.pjaZTi7GTxrDTN32pw-qPl9ZRNg2CUIQ2vlV0MPkC0SCznIOWibdlV4re14YorS-c_3sYXI3UEqwkBkYA2GYaPVxdethWz4Qf_JWPe6bqj5u7CroQP3DkoaqKDEKo04s6yh0ZF3WQsJtFUuNQ53J0JSCntHQ7YfSYVZpaZY2mJ3wI792PkAqULMBaUdO6rFWtg_Nh0kdhKqfkS7JO4fSiJUlNbeGOYre2YQ8IJ3n7aM4RNWtVxbUAlQG6Hnj99SO2QpF-KfLheRhnipHTXCjgX2RMCQIIlkVE6KdSyQ-pYxXTNj99YHdNNkc4BS5306EpnBJ4CorLGkWV46HK1sv9A

###########################################
# Auth

### /auth/login
POST {{Host}}/auth/login
content-type: application/json

{
    "email": "user@example.com",
    "password": "Password@1234"
}


### /_authcheck
GET {{Host}}/_authcheck
Authorization: Bearer {{AccessToken}}


### /auth/sign-up
POST {{Host}}/auth/sign-up
content-type: application/json

{
    "email": "johnsmith@foobar.net",
    "password": "Password@1234",
    "firstName": "John",
    "lastName": "Smith",
    "groupName": "",
    "tos": "2024-04-16"
}


###########################################
# User

### /user
GET {{Host}}/user
Authorization: Bearer {{AccessToken}}


### /user
POST {{Host}}/user
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "firstName": "Alex",
    "lastName": "Jones"
}


### /user/update-password
POST {{Host}}/user/update-password
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "password": "Password@1234",
    "newPassword": "NewPassword!4321"
}
